export {default as Header} from './header/Header'
export {default as Download} from './download/Download'
export {default as Faq} from './faq/Faq'
export {default as Feature} from './feature/Feature'
export {default as Subscribe} from './subscribe/Subscribe'
export {default as Footer } from './footer/Footer'
export {default as Navbar} from './navbar/Navbar'